# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: aedeeb3e87775e61a365e55ff5123ee3fd958c19263be37e2a58e74bf59c23fb7827963bf55542301fb2a8490a2386dbbe9b655fc7cd270e3675809b1a8af2d6

test:
  secret_key_base: 263a2d94b883935d1957c57ac3bd9a03052f78f85a5257c8cef4501b7c454446778ecf312403b2f9b02dc16edf785fdb25fb3f3b06d0ad9daf66067e95d6d823

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
